apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels: 
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/postgres # This is the path on the host where the data will be stored
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "postgres"
