apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc }}